# Generated by Django 6.1.1 on 2026-09-21 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20, unique=True)),
                ('account_type', models.CharField(choices=[('Savings', 'Savings'), ('Current', 'Current'), ('Fixed Deposit', 'Fixed Deposit')], max_length=30)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('account_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Closed', 'Closed')], default='Active', max_length=20)),
                ('opened_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_accounts', to='customers.customer')),
            ],
        ),
    ]
